#!/bin/bash
set -e

cd "$(dirname "$0")"

echo "Building WASM..."
tinygo build -o pixelid.wasm -target=wasm -no-debug -panic=trap .

echo "Copying wasm_exec.js..."
cp "$(tinygo env TINYGOROOT)/targets/wasm_exec.js" wasm_exec.js

echo "Generating base64 embed..."
BASE64=$(base64 -i pixelid.wasm)
cat > ../ts/src/wasm-binary.ts << EOF
// Auto-generated by wasm/build.sh — do not edit.
export const WASM_BASE64 = "${BASE64}";
EOF

echo "Copying wasm_exec.js to ts/src..."
cp wasm_exec.js ../ts/src/wasm_exec.js

SIZE=$(wc -c < pixelid.wasm | tr -d ' ')
echo "Done. WASM binary: ${SIZE} bytes"
